revelc/formatter-maven-plugin

pom.xml

Use same org.eclipse.jdt.core version as in Eclipse Oxygen.1a (4.7.1a)

---

CHANGELOG.md
README.md
appveyor.yml
pom.xml

* Update to Eclipse Photon
* Update plugin versions
* Update dependency versions
* Add comments explaining beanutils dependency

Update plugin versions and support Photon

---

pom.xml
src/main/java/net/revelc/code/formatter/FormatterMojo.java
src/main/java/net/revelc/code/formatter/xml/XMLFormatter.java
src/main/resources/formatter-maven-plugin/eclipse/xml.properties
src/test/java/net/revelc/code/formatter/xml/XMLFormatterTest.java
src/test/resources/someFile.xml

Replaces jsoup with revelc's [xml-formatter](https://github.com/revelc/xml-formatter)

Adds xml-formatter

---

src/main/java/net/revelc/code/formatter/xml/XMLFormatter.java
src/main/resources/formatter-maven-plugin/eclipse/xml.properties

Just updating the default properties after having upgraded the xml-formatter

updates xml-formatter properties

---

src/main/java/net/revelc/code/formatter/FormatterMojo.java

Make 'excludes' a user property, same as 'includes'.

make 'excludes' a property

---

src/main/java/net/revelc/code/formatter/FormatterMojo.java

these have valid defaults already and do not require wrapper class.

[ci] Change maven injections to 'boolean' instead of 'Boolean'

---

src/main/java/net/revelc/code/formatter/FormatterMojo.java

Use target/ directory for default cachedir

---

CHANGELOG.md
pom.xml
src/main/java/net/revelc/code/formatter/AbstractCacheableFormatter.java
src/test/java/net/revelc/code/formatter/css/CssFormatterTest.java
src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java

Rework logic for end of line processing fixes #531

---

CHANGELOG.md
src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
src/test/resources/someFile.html

we are only seeing one time pass here until other issues fixed but this shows that it doesn't just add extra lines like it does in current release.  Upstream was fixed on jsoup for this.

[html] Add in <script> tag to html page to confirm it validates properly without breaking formatting

---

src/main/java/net/revelc/code/formatter/AbstractCacheableFormatter.java
src/main/java/net/revelc/code/formatter/FormatterMojo.java
src/main/java/net/revelc/code/formatter/LineEnding.java
src/main/java/net/revelc/code/formatter/Type.java
src/main/java/net/revelc/code/formatter/css/CssFormatter.java
src/main/java/net/revelc/code/formatter/java/JavaFormatter.java
src/main/java/net/revelc/code/formatter/javascript/JavascriptFormatter.java
src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
src/main/java/net/revelc/code/formatter/jsoup/JsoupBasedFormatter.java
src/main/java/net/revelc/code/formatter/model/Profile.java
src/main/java/net/revelc/code/formatter/model/Profiles.java
src/main/java/net/revelc/code/formatter/model/RuleSet.java
src/main/java/net/revelc/code/formatter/xml/XMLFormatter.java

trying to keep manageable as used Eclipse to do in mass.

[ci] Code qualifications / more finals

---

src/test/java/net/revelc/code/formatter/AbstractFormatterTest.java
src/test/java/net/revelc/code/formatter/LineEndingTest.java
src/test/java/net/revelc/code/formatter/TimeUtilTest.java
src/test/java/net/revelc/code/formatter/css/CssFormatterTest.java
src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
src/test/java/net/revelc/code/formatter/java/JavaFormatterTest.java
src/test/java/net/revelc/code/formatter/javascript/JavascriptFormatterTest.java
src/test/java/net/revelc/code/formatter/json/JsonFormatterTest.java
src/test/java/net/revelc/code/formatter/model/ConfigReaderTest.java
src/test/java/net/revelc/code/formatter/xml/XMLFormatterTest.java

static issue may be contensious but is really bad usage when not very many as it loses clarity.  Sure most know what it means but beginners need to see it easier.  Plus Eclipse is rather firm to this.

[tests] Run full code cleanup here

---

LICENSE
src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
src/test/resources/someFile.html

there is one left but its not a valid side so I just left it alone plus that file (css file) tends to lock up my Eclipse to the point I have to kill it so I figured not worth the effort there since it points to no valid side.

Last of http to https

---

CHANGELOG.md

added recent items missed on change log.

[ci] Add more to change log for internal work

---

pom.xml
src/main/java/net/revelc/code/formatter/AbstractCacheableFormatter.java
src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
src/test/java/net/revelc/code/formatter/json/MultipleJsonFormatterTest.java
src/test/java/net/revelc/code/formatter/json/NormalJsonFormatterTest.java
src/test/resources/multiple-json/after.json
src/test/resources/multiple-json/before.json
src/test/resources/normal-json/after.json
src/test/resources/normal-json/before.json

https://github.com/revelc/formatter-maven-plugin/issues/594

support multiple-object json file

---

pom.xml

allows us to release again.  Code line is the same outside of some minor pull requests not yet merged to jsoup that are used for the overall build.

Move to fork of jsoup until jsoup team releases code

---

src/main/java/net/revelc/code/formatter/css/CssFormatter.java
src/test/java/net/revelc/code/formatter/css/CssFormatterTest.java

Resolves issue noted with css processing.  Our file had the same issue.  Reused code already present to do similar on jsoup processing of html.

[css] Add empty new line at end of file

---

pom.xml
src/main/java/net/revelc/code/formatter/xml/XMLFormatter.java
src/main/resources/formatter-maven-plugin/eclipse/xml.properties

All fields are now primatives, rewrite more tightly here as no reason to have separated.  Add support for deleteBlankLines.

[enhance] Add support for xml-formatter 0.3.0

---

src/main/java/net/revelc/code/formatter/model/ConfigReader.java

Hi
there is a line where is checked the "result" var.
But there are 2 checks: not instance of and null check
But if the variable is null, it is true also the not instance of
For this reason I have removed the null check test in the if statement
ciao
matteo

null variable is not instance of profile. Removed double check

---

pom.xml
src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
src/test/java/net/revelc/code/formatter/json/JsonFormatterTest.java

Update libraries and fix hash on tests for jsoup/jackson updates

---

src/main/java/net/revelc/code/formatter/FormatterMojo.java

[cache] Rewrite cache based of improved work from impsort port of similar logic

---

pom.xml
src/main/java/net/revelc/code/formatter/FormatterMojo.java

further work to try to get off plexus utils.

Replace plexus utils usage of string utils with commons lang 3 and make lang 3 compile time now

---

pom.xml
src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java

Change is > something < is now >something< - note spaces.  Change is valid, applied update to cache.

[pom] Bump jsoup to 1.18.1

---

src/main/java/net/revelc/code/formatter/FormatterMojo.java

buffered items can be retrieved more directly
additionally clarify variables for readability

Rewrite more of java.io to java.nio
