revelc/formatter-maven-plugin

- src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
- src/test/java/net/revelc/code/formatter/AbstractFormatterTest.java
- src/test/java/net/revelc/code/formatter/json/JsonFormatterTest.java
Fixed issue #279.
This feature can be toggled using an additional property into `configJsonFile`
```
spaceBeforeSeparator=false  <-- default value is true
indent=4
```
> Fix for issue #279: Allow JSON formatter to omit space before separator

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
I'd like to propose a change that will eliminate the whole class of build issues - source code formatting with wrong rules in case of missing config file. Had this issue with config file as a url and the lack of Internet connectivity. This issue is mentioned here as well - https://github.com/revelc/formatter-maven-plugin/issues/275
> fail fast in case the config file cannot be found

- src/main/java/net/revelc/code/formatter/java/JavaFormatter.java
- src/main/java/net/revelc/code/formatter/javascript/JavascriptFormatter.java
Use ToolFactory.M_FORMAT_EXISTING when creating the code formatters, in
order to ensure that all options which preserve existing comment
indentation (or lack thereof) are respected.
See Javadoc for ToolFactory.M_FORMAT_EXISTING
And also: https://bugs.eclipse.org/bugs/show_bug.cgi?id=415630
> Fix #288 Ensure comment indent options are used

- pom.xml
- junit to 5.4.0
- guava to 27.1-jre
- plexus-utils to 3.2.0
- jdt core to 3.17.0
- surefire to 3.0.0-M3
- Update comment regardle fluido for clarity as it used to apply to the dependency after it as well.
> Update dependencies including Eclipse IDE 2019-03 release 

- .travis.yml
- CHANGELOG.md
- pom.xml
Fix #301 Resolve version ranges in transitive deps
Add `<dependencyManagement>` section to explicitly resolve transitive
dependency ranges from JDT core dependency for build reproducibility and
to avoid unnecessary Maven resolution on CI servers or when `mvn -U` is
specified.
Update plugin and dependency versions
* Update JDT to 3.18 (Eclipse 4.12, 2019-06)
* Update other dependencies
* Update plugins
> Update plugin and dependency versions

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- pom.xml
- src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
* Require JDK11 for building (still targeting Java 8 as minimum runtime)
* Update jdt.core for Eclipse 2019-09
* Resolve transitive dependency ranges of jdt.core to updated versions
* Update CI tooling for Maven 3.6.2 and JDK11
* Update jackson and fix JsonFormatter to work with new version
* Update other plugins and dependency versions to latest
* Update xml-formatter library to 0.2.0, which provides new options for
handling xml files without DTD validation or otherwise fail to parse
> Updates for Eclipse 2019-09

- src/main/java/net/revelc/code/formatter/AbstractCacheableFormatter.java
This is done because when looking at logs from
a bunch of files it's hard to determine what actually
happened and make assumptions based on the absence of
log messages.
> Add log about fixed line endings

- src/site/apt/examples.apt.vm
Moved the `<configuration>` tag outside of the `<execution>` tag.
This simple update to the examples allows the plugin to run when the execution binds to a lifecycle phase or can also be run manually using `mvn formatter:format` which will not collect configuration specified within an `<execution>` tag.
Discussed in issue #321
> Update <configuration> location in examples.

- pom.xml
- note added jackson annotations directly as they refuse to keep the underlying using that ever aligned release.  This ensures we have same version.  Seems silly on their part since they keep releasing it but they have discussed stopping that release and there was a lot of push back for this very reason.  Not ideal but not entirely bad to keep in sync on our part.
- jsdt-core update to 2.7.1 is not in this yet as I just released it.  I'll follow up with that in next few hours.  With stability of travis questionable when that occurs, want to hold until it's in all release channels.
- modernizer supports up to jdk 15 now.  However, it uses a legacy setup.  Since we require jdk 9 to build, the compiler options that are deprecated are not used so I removed them.  I adjusted this to use the …
> Bring all libraries up to date, moderizer config change, remove deprecated compiler options

- src/main/resources/formatter-maven-plugin/eclipse/xml.properties
And change default to 120 characters to match all our other formatting plus terminals are way bigger these days and really probably should be higher.
> [config] Sort the xml configuration properties + default to 120 characters

- .gitignore
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
New logic to longer live the cache.  This allows continued builds to stop reformatting files if unnecessary.  The cache will live longer and as such it will be looked up first before any attempt to format at all times unless cache is deleted.  This speeds up initial processing.
> [ci] Move cache file to basedir in folder .cache

- .github/dependabot.yml
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
For those that might want to check in the caching files and have automation that might otherwise re-commit since java properties always adds a timestamp entry, this will prevent such a case.  While it doesn't speed things up much, it at least avoid unnecessary write all together.
> Enhance - do not write the cache file if it did not change

- CHANGELOG.md
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/main/java/net/revelc/code/formatter/Type.java
If you skip certain types of files from formatting and your project have some files of those types then one message per file saying `<type> formatting is skipped` is written on the maven console log providing no value (in part because it does not specify which file was skipped as it is shown on `debug` level).
This change put those logs at the same log level (`debug`) as the one that shows which file is being processed so you have the same information but with the proper context and only when you want to debug some case.
As a replacement for the multiple log messages and to keep providing a way to quickly debug misconfiguration a single log line with all the types skipped from formatting is added as `INFO` level (`Formatting is skipped for types: XML, HTML, ...`)
Also, it corrects the …
> Change log level for "<type> formatting is skipped" messages

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
Use `System.nanoTime()` instead of `System.currentTimeMillis()` for
computing relative time intervals correctly. Nano-time is not useful for
absolute time, but it is better for relative time/durations, because the
difference between one time and a subsequent time is always positive and
not affected by system clock changes.
> Use nanos for correct duration calculations

- pom.xml
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
* Bump formatter to latest release for current build
* Update the javadoc for the cache to warn about changes a user might
make that would invalidate any cache (re #453)
> Bump plugin and update cache javadoc

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
In some rare use case it could be good to use the plugin outside the project to format. For example when all the project don't share the same parent pom we could use a generic pom to automatically format code at pre commit like [this](https://github.com/brun-nico/formatter-maven-plugin).
To do that it's necessary to specify the base directory because in this case the base directory isn't equal to project.basedir.
> Add capacity to use a custom base diretory

- CHANGELOG.md
- pom.xml
- src/site/markdown/eclipse-versions.md.vm
* Bump JDT Core to 3.26
* Bump JDT Core's transitive dependencies
* Update compatibility doc and CHANGELOG
* Also bump maven-dependency-plugin
> Bump dependencies for Eclipse 2021-06

- src/main/java/net/revelc/code/formatter/css/CssFormatter.java
- src/test/java/net/revelc/code/formatter/css/CssFormatterTest.java
fixes #522 
An old IE css hack that uses \9; is failing with the formatter as it is first translated to a tab then subsequent passes delete it entirelly.  Because our own test file had this specific hack logic, we should fix as we are formatting logic not trying to rewrite logic incorrectly.  There is a given that ie 7,8,9 is likely not used but also these usually come in pairs and file maintainer should remove any ie hacks on their own.  The changes implied by auto doing that could cause differences in css usage across all browsers as it would duplicate entries.
> [css] Add patch to retain \9 during css formatting as cssparser conversions fixes #522

- src/test/java/net/revelc/code/formatter/AbstractFormatterTest.java
- src/test/java/net/revelc/code/formatter/FormatCycle.java
- src/test/java/net/revelc/code/formatter/css/CssFormatterTest.java
- src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
- src/test/java/net/revelc/code/formatter/java/JavaFormatterTest.java
- src/test/java/net/revelc/code/formatter/javascript/JavascriptFormatterTest.java
- src/test/java/net/revelc/code/formatter/json/JsonFormatterTest.java
- src/test/java/net/revelc/code/formatter/xml/XMLFormatterTest.java
Fixes #523 
Currently we do a single pass of formatting.  This itself does not prove our formatting is actually valid.  We need a second pass that processes the files formatted in the first pass to ensure they result in same output.  This was needed to further track down issue with html processing and also flushed out issue in css processing.
> [tests] Rewrite all tests to do two passes and always write file results to disk before assertion checks - fixes #523

- .github/workflows/maven.yaml
- pom.xml
This reverts the change in #529 and restores the processing of licenses
as part of CI tasks. However, drop the optional processing of git
information to populate unused variables for the license header
template.
> [ci] Restore license checking, omit git tasks

- pom.xml
Build for Java 11 because JDT dependencies require 11 or later
The plugin won't currently work for versions prior to 11 because of
the dependencies, so this ensures the plugin itself also targets 11.
> Build for Java 11

- CHANGELOG.md
- README.md
- pom.xml
- src/site/markdown/eclipse-versions.md.vm
* Bump JDT Core to 3.28
* Bump JDT Core's transitive dependencies
* Update compatibility doc and CHANGELOG
> Bump dependencies for Eclipse 2021-12

- CHANGELOG.md
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
The new whitespace trim logic falls outside the stats block but is still formatting.  Moved this up so that it is included in counts.
notes:
- We don't have tests that perform a true formatting so we should think about adding integration tests at some point using invoker.  I noticed this while working on jsoup as it doesn't hit this logic via the unit tests then realized we were never actually testing this directly.  It works fine, just needs to be in the right spot.
- We should consider making this default behaviour rather than opt in.  Its purpose is to fix bugs with javadoc but at the moment also fixes bugs with jsoup on html (which may end up fixed in jsoup but noting that here).
> [rework] Make sure trailing space removal is counted as formatting

- CHANGELOG.md
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
We are formatting, this doesn't make sense to opt into and would result in potentially requiring us to patch jsoup for example and maybe others.
> [default] Change remove trailing whitespace default to 'true'

- .github/workflows/maven.yaml
- CHANGELOG.md
- pom.xml
- src/main/java/net/revelc/code/formatter/jsoup/JsoupBasedFormatter.java
- src/main/resources/formatter-maven-plugin/jsoup/html.properties
- src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
hashes are slightly different as it changes 3 lines to have ending tag </ending> instead of />.   It does improve what appears to have been a double header getting added.  Will keep this setup this way for a bit while testing out more localized items including a temp code patch that will be coming here so our tests work while jsoup is working out why they don't trim properly so I can turn on dual tests here during further testing.
> Allow all branches to build on actions, use jsoup snapshot 1.15.1, and add repo to allow it

- CHANGELOG.md
- src/main/java/net/revelc/code/formatter/jsoup/JsoupBasedFormatter.java
- src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
Technically this one is a duplicate due to lack of our tests running in full and picking up the javadoc patch that does same.  In order to try to move this forwards, this is in here with a // TODO so we can remove it later when Jsoup fixes issue.  I have reported it, they stated fixed, I reported still broken, was told they would look more but heard nothing back.  So for now I'm giving up to get this in place.
> [jsoup] Add an internal patch to trim trailing whitespace so our tests work

- CHANGELOG.md
- src/main/java/net/revelc/code/formatter/jsoup/JsoupBasedFormatter.java
- src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
Jsoup fails to count their indenting properly.  While they have a website to send test data for them to review they do not expose all the parameters.  So anything with 1 character indent is fine.  Its all the other indents that have issues.  The first commit here can be ran on its own still in single test mode then look at resulting second html page.  It will get extra 1 character on quite a number of lines.  Typically those are tag breaks with data on the second line.  This fix iteslf is extermely ugly but resolve the issue which I don't think jsoup is going to resolve.  They closed my original ticket stating fixed but I asked to reopen as not fixed.  They said they were looking but that was first week in November so nothing since and we are on the latest snapshot.  So like the others …
> Fix joup counting issue.

- .github/workflows/it.yaml
- CHANGELOG.md
- README.md
- pom.xml
- src/it/cache/invoker.properties
- src/it/cache/pom.xml
- src/it/cache/src/main/java/net/revelc/code/formatter/cache/CacheSample.java
- src/it/cache/src/main/java/net/revelc/code/formatter/cache/CacheSample2.java
- src/it/cache/src/main/java/net/revelc/code/formatter/cache/CacheSample3.java
- src/it/cache/src/main/java/net/revelc/code/formatter/cache/package-info.java
- src/it/cache/verify.groovy
- src/it/settings.xml
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- Sort and removal of timestamp do not appear to delay processing enough right now to warrant adding more if caching is being used.  Can follow up if we have more data to show that has any substantial impact.
- Sort and timestamp ensure that any unexpected write of file will not change the file if nothing changed.  This is prominant on maven plugins with help mojo as maven sets that in generated sources which is then picked up by formatting then promptly is moved by maven after plugin-plugin run.  This behaviour causes the current protections to see that formatting occurred and as such write the cache.  The cache itself is a properties file so it suffers from two major issues.  The first being the timestamp is added everytime it is written which is problematic at best and cannot be …
> Add sort and removal of timestamp from cache file for fuller automation / repeatability / First integration test

- pom.xml
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/main/java/net/revelc/code/formatter/ValidateMojo.java
This plugin is used extensively in Quarkus and new contributors
are often left unsure of what to do when they see the validation
error message.
This change provides users with an explicit command to run when the
validation fails
> Provide actionable error message when validation fails

- pom.xml
- src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
- patches applied
- fixes additional spacing issue
- fixes duplication on license header
> [pom] Move back to upstream jsoup 1.15.2

- src/main/java/net/revelc/code/formatter/jsoup/JsoupBasedFormatter.java
- src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
- Use XXX rather than TODO as entries are not really todo's but need called out if upstream fixes
- Pull up line ending normalization as jsoup will cause non normalized data during its process even if file was previously normalized.  This was mixed into another fix.
- Add clarifications within index counter fix.  Issue typically shows up on span, div, a, possibly others where it still adds one extra space in violations to what was asked for index size
- Removed header line break fix as that was fixed in the fork we used and now also fixed in jsoup directly
- Add new line to end of the file
The existing checks were all verified to still be considerations that have not yet been fixed in jsoup pretty print.  There are 4 patches as follows:
- Removal of trailing space on each line
- …
> Jsoup follow-up formatting patches

- pom.xml
project uses dependabot only and report section for this was removed previously
> [pom] Remove versions plugin from dep management as no longer used

- CHANGELOG.md
- pom.xml
- src/site/markdown/eclipse-versions.md.vm
* Bump JDT Core to 3.31.0
* Bump transitive dependencies for JDT Core using src/build/find-transitive-eclipse-updates.sh script, but leave osgi at 8.1.0 and not 8.0.1 (apparently, Eclipse still depends on 8.0, but 8.1 works fine). Also note that the JDT Core POM model is incorrect and says 4.0, when it should be 4.0.0. This caused a parse error running this script, but was trivial to patch the POM temporarily to get the script to work
* Update Jackson to latest patch release
* Update JUnit to altest
* Update version table for website and CHANGELOG
> Bump dependency versions for Eclipse 2022-09

- pom.xml
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
resolves #672
Signed-off-by: James R. Perkins <jperkins@redhat.com>
> [672] Add a parameter for including resources when formatting.

- pom.xml
commons-logging as independent library is long obsolete and should not come into our stack.  Given maven is slf4j based, use jcl-over-slf4j as a direct replacement so that logging, if any, actually is picked up from that transient usage.
Update few other dependencies recently released.
> Align usage better with maven slf4j usage, bump few versions

- CHANGELOG.md
- pom.xml
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/site/markdown/eclipse-versions.md.vm
* Bump plugin versions and dependencies
* Bump prerequisites to 3.5.0
* Fix warning in license-maven-plugin for old style config
* Fix Maven warning about how to mark project component in mojos
> Update for Eclipse 2023-03

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/main/resources/formatter-maven-plugin/eclipse/java.xml
* Update provided java.xml Eclipse JDT formatter config for 2023-03
* Review javascript.xml for the same, but no changes
* Fix minor typo in spelling of 'eclipse' in a log message
> Review and update provided Eclipse configs

- pom.xml
This is still in the maven-plugin project but 'report' is now deprecated and last 3 releases this was the new support.  With new maven 3.9.0 to show warnings, it became clear it was switched.  Made appropriate change here - nothing else to change.
> [pom] Upgrade to non deprecated maven plugin report plugin 3.8.1

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/main/java/net/revelc/code/formatter/Type.java
- src/main/java/net/revelc/code/formatter/ValidateMojo.java
- src/main/java/net/revelc/code/formatter/css/CssFormatter.java
- src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
- Use immutable lists
- Use jdk strings over guava
- Use -1 on split to behave as guava would without surprises
- Remove mojo execution from validate mojo as not used.
> [cleanup] Fix all error prone issues

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/main/java/net/revelc/code/formatter/java/JavaFormatter.java
Include the formatting configuration in the hash calc as per https://github.com/revelc/formatter-maven-plugin/issues/453
If you're happy with the approach I'll do the same for the other formatters.
> Cache config

- pom.xml
- src/site/markdown/eclipse-versions.md.vm
I hope I did everything correctly ☺️
>  Update for Eclipse 2023-12

- README.md
- pom.xml
Version 2.24.0 will require JDK 17, so this change makes it the runtime target version, so that it explicitly requires JDK 17, for fast failure and errors don't show up later unexpectedly when calling into the Eclipse libraries at runtime. Also update the README. Notably, the website docs were already updated to indicate it is required as part of the PR #812
> Require JDK 17 explicitly in POM and README

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
Do not initialize Json formatter with KEEP line ending. Instead, ensure that the output replaces the default lineendings with the user's preferred endings, whether it's specified or detected by KEEP.
This fixes #827
> Fix JSON handling of LineEnding.KEEP

- pom.xml
Parent poms that don't exist up one level, they need to not look up one level but instead look to m2 cache immediately.  In my case I have a pom level one up that is for cleaning my workspace and maven will issue configuration warnings stating this must be added and its best practice when using a parent pom that is not in same project.
> [pom] Add missing relativePath set to nothing

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
Error notes all 6 formatters but only 5 were being checked.  Corrected so all 6 are checked.
> [fix] Add missing check for json to config checks

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/main/java/net/revelc/code/formatter/css/CssFormatter.java
- src/main/java/net/revelc/code/formatter/java/JavaFormatter.java
- src/main/java/net/revelc/code/formatter/javascript/JavascriptFormatter.java
- src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
- src/main/java/net/revelc/code/formatter/jsoup/JsoupBasedFormatter.java
- src/main/java/net/revelc/code/formatter/xml/XMLFormatter.java
fixes #757
Original change in d1d5852 only addressed java and did so at detriment of all formatters.  This caused certain platforms to continually update the cache file on every build.  As seen on GitHub, Linux and Macos would change the *nix hashes for every file constantly including java.  For Windows on Github, it was changing the entire file (not clear as to why entire file but that was observed over and over).  Testing to show issue was done with 2.23.0 formatter release that introduced the problem.
> [caching] Rewrite d1d5852 fixing #757

- .github/workflows/maven.yaml
See https://github.com/actions/setup-java?tab=readme-ov-file#caching-packages-dependencies as this is built in now.
> [GHA] Change caching to built in from setup-java

- pom.xml
slf4j overrides maven, it must remain the same revision.  When it is not, the service loader will not properly find the version used and throws warnings with slf4j.  In this case, test on simple is required as its the test that runs into the issue.  This produces a proper stack trace after resolved.
Dependabot will need to be informed on this repo to not suggest 2.x.  We an only upgrade when maven does or we override maven entirely which historically has not been the intent of this repo.
> [tests] Add slf4j-simple to tests to clear warnings and correct jcl version to 1.7.36

- pom.xml
Plexus utils 4.0.0 brings in maven 4 apis which should not be in the build.  In many cases it breaks compatibility with maven 3 especially earlier versions indicated supported here.  Maven created a non maven 4 copy of plexus-xml that should be defined for this specific purpose.  We should however try to stop relying on plexus utils as its mostly deprecated.
> [pom] Use plexus xml 3.0.0 or we lose maven 3 support

- pom.xml
Commons-logging is bad from the beyond.  It now understands slf4j and log4j2.  There are efforts now to deprecate jcl-over-slf4j, log4j-jcl, and spring-jcl in favor of this which is built from how spring-jcl worked.
- https://github.com/qos-ch/slf4j/issues/403
- https://github.com/apache/logging-log4j2/issues/2251
- https://github.com/spring-projects/spring-framework/issues/32459
> [pom] Use commons-logging again instead of jcl-over-slf4j and cleanup

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
- src/main/java/net/revelc/code/formatter/ValidateMojo.java
- src/main/java/net/revelc/code/formatter/css/CssFormatter.java
- src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
- src/main/java/net/revelc/code/formatter/jsoup/JsoupBasedFormatter.java
'var' is not hard to understand.  Its already stating directly what it is by the right hand side.  This is still type safe.  Further its just the opposite of diamond operation.  Java provided this for a valid reason, we end up with less imports, cleaner code, and lose nothing using it.
This was already done in mass a long time back because code base moved above java 10.  Being consistent at this point as very little is not done.
> [var] since majority of 'var' is used, used the rest

- .github/workflows/maven.yaml
we need to show our repo works with newer jdks, not just the min one.  Move from zulu to temurin.  And add macos-14 as that is the m1 chip.
> [GHA] Run in far more instances

- pom.xml
Modified delivery of this artifact now only includes what is necessary which reduces size of jar from 35mb to 5mb.
> [pom] Bump jsdt-core to 3.4.2

- pom.xml
- src/test/java/net/revelc/code/formatter/xml/XMLFormatterTest.java
- src/test/resources/someFile.xml
comments are handled differently in latest release fixing long standing issue that kept tabbing over  Adjusted the test here to show messed up comment to ensure it got corrected.
> Bump xlm formatter to 0.4.0

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
> [894] Use the formattedCode for the formattedHash.

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
This logic seems flimsy.  For now, just labeled it for what it is.  I think though we need to add extra item to properly track caching changes if formatting failed to do anything.
> [ci] Comment on what unchanged is

- pom.xml
- src/site/site.xml
Site xsd was wrongly implemented and site.xsd requires site 4 milestones and fluido 2 milestones.  Fixed all that then enabled site to generate from maven.  The upstream site should be removed.  Its 9 years old and not supported.  For single module projects, maven's site generates and releases ok.  The 2.24.0 release didn't push any release for site and it appears to have been manually done for 2.23.0.  This should fix it so it generates properly.  The results looked the same when I spot checked the entire thing.  The comments to remove items would apply once upstream joins using modernized site deployment via maven release (again for single modules, its still entirely broken for multi module).
> Use maven to deploy site

- pom.xml
actual issue is all the overrides on release that are not needed.  Fall to scm as that is the standard way maven suggests now even though release wants site.  Reduced version of what I use in hazendaz/base-parent just enough to get it to go.  The release still won't do it but left instructions on here to do this on demand.  Takes maybe minute or two.  Site is now updated which is an improvement.  This alone below will do nothing without running the commands listed.
> [pom] Site still did not release, add scm data to allow it to occur

- pom.xml
eclipse compare core for some reason was many years old.  Its updated to latest now.
performed manually as shell script requires additional software xmllint and issues with windows line endings.
> [pom] Update to latest eclipse binaries *

- src/main/java/net/revelc/code/formatter/json/JsonFormatter.java
- src/test/java/net/revelc/code/formatter/json/JsonFormatterTest.java
Fixes JSON formatting issue #929, namely, fixes field separator initialization as to Jackson v2.17 API.
> Adapt field separator initialization to Jackson v2.17 API (#929)

- pom.xml
- src/main/java/net/revelc/code/formatter/FormatterMojo.java
maven has deprecated component now.
> [maven] Update from component to inject per jsr330

- src/test/java/net/revelc/code/formatter/AbstractFormatterTest.java
Simple toString will do what we were doing on our own.
> Simplify our hashing verification check in tests

- pom.xml
- Bump jdt core to 3.40.0
- Bump jsdt core to 3.5.0
- No longer exclude any libraries unless 100% necessary as tools do not show relationships and dependency convergence is on
- Do not worry about libraries we vetted that are ok with dependency convergence issues
- Drop part of the osgi overrides as no longer needed
- Use the last cglib to avoid any potential issues (at least until apache commons team finally releases digester upgrade after 14 years)  I expect this to be removed at that time.
- Override asm for same reason as cglib (the only required exclusion is here because group id change).  I expect this to be removed once digester new release is made.
- Adjust comments around how we handle convergence or override usage
- Drop commons lang3 as it was used once to check for empty, just …
> Rewrite pom for better support along with updating outstanding library versions

- src/main/java/net/revelc/code/formatter/FormatterMojo.java
the FormatterMojo::formatFile was only called once and did not contain complex logic. inlining improves readability by eliminating an extra code jump.
> [refactor] inline FormatterMojo::formatFile into FormatterMojo::execute to remove unnecessary indirection

- pom.xml
- src/test/java/net/revelc/code/formatter/html/HTMLFormatterTest.java
General difference is that ```<div>``` if possible will be same line and some tags content that had extra space at front and end of the text are now without that space.  No issues seen otherwise and only improvements as noted with html5 support compliance on jsoup github.
> Bump jsoup to 1.20.1 and adjust tests to allow changes

- pom.xml
- src/site/markdown/eclipse-versions.md.vm
Also update errorprone annotations because a newer one was available
> Update JDT for Eclipse 2025-06
